In [23]:
import torch
import torch.nn as nn


class Net(nn.Module):
    # 모델의 구성 요소 생성 및 구조 설정
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.drop = nn.Dropout(0.5)
        self.fc3 = nn.Linear(2, 1)

    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.fc3(self.drop(self.fc2(self.fc1(x))))


In [24]:
from torchinfo import summary

model = Net()

print(model)

summary(model)


Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (drop): Dropout(p=0.5, inplace=False)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Dropout: 1-3                           --
├─Linear: 1-4                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [2]:
## 모델 인스턴스 생성
model = Net()


In [6]:
## 모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.fc1.weight, model.fc1.bias


(Parameter containing:
 tensor([[-0.0021, -0.1120, -0.2482, -0.0970, -0.0647,  0.2996,  0.1490, -0.0564],
         [ 0.0359,  0.0087, -0.0895,  0.0281,  0.1194,  0.2672,  0.1577, -0.0921],
         [-0.1676,  0.0260, -0.2375,  0.0394, -0.2164, -0.0984,  0.1164,  0.1717],
         [ 0.0183,  0.0503,  0.1859,  0.0784, -0.3048,  0.1734, -0.0094, -0.1519]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0439, -0.0806,  0.2727, -0.2666], requires_grad=True))

In [4]:
# 모델의 각 층별 W, b 텐서 정보 확인
for parm in model.parameters():
    print(parm, end="\n\n")


Parameter containing:
tensor([[-0.0021, -0.1120, -0.2482, -0.0970, -0.0647,  0.2996,  0.1490, -0.0564],
        [ 0.0359,  0.0087, -0.0895,  0.0281,  0.1194,  0.2672,  0.1577, -0.0921],
        [-0.1676,  0.0260, -0.2375,  0.0394, -0.2164, -0.0984,  0.1164,  0.1717],
        [ 0.0183,  0.0503,  0.1859,  0.0784, -0.3048,  0.1734, -0.0094, -0.1519]],
       requires_grad=True)

Parameter containing:
tensor([ 0.0439, -0.0806,  0.2727, -0.2666], requires_grad=True)

Parameter containing:
tensor([[ 0.0782, -0.4832,  0.1487,  0.2208],
        [ 0.2517,  0.3916, -0.4040,  0.3712]], requires_grad=True)

Parameter containing:
tensor([ 0.2174, -0.1971], requires_grad=True)

Parameter containing:
tensor([[-0.2627, -0.0052]], requires_grad=True)

Parameter containing:
tensor([0.4522], requires_grad=True)



In [5]:
for parm in model.named_parameters():
    print(parm, end="\n\n")


('fc1.weight', Parameter containing:
tensor([[-0.0021, -0.1120, -0.2482, -0.0970, -0.0647,  0.2996,  0.1490, -0.0564],
        [ 0.0359,  0.0087, -0.0895,  0.0281,  0.1194,  0.2672,  0.1577, -0.0921],
        [-0.1676,  0.0260, -0.2375,  0.0394, -0.2164, -0.0984,  0.1164,  0.1717],
        [ 0.0183,  0.0503,  0.1859,  0.0784, -0.3048,  0.1734, -0.0094, -0.1519]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([ 0.0439, -0.0806,  0.2727, -0.2666], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[ 0.0782, -0.4832,  0.1487,  0.2208],
        [ 0.2517,  0.3916, -0.4040,  0.3712]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([ 0.2174, -0.1971], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[-0.2627, -0.0052]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([0.4522], requires_grad=True))



In [16]:
# 모델 구성 모든 Layer 가져오기
for child in model.children():
    print(child, end="\n\n")

for child in model.named_children():
    print(child, end="\n\n")


Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))



-   Layer의 가중치 설정


In [12]:
# 세이비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.fc1.weight)


Parameter containing:
tensor([[ 0.3689,  0.3079, -0.1480,  0.1316,  0.2490,  0.0149, -0.4430, -0.6273],
        [-0.1912,  0.1250, -0.0652, -0.3685,  0.4212,  0.1478,  0.6177, -0.1721],
        [-0.1503,  0.2035,  0.2944, -0.4188,  0.1718,  0.4152,  0.5445,  0.0068],
        [ 0.4889,  0.1658, -0.5495, -0.4628, -0.3741,  0.2029,  0.3915, -0.3051]],
       requires_grad=True)

In [13]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.fc2.weight)


Parameter containing:
tensor([[ 1.0253,  0.3091, -0.3823,  1.2523],
        [-0.6222, -0.0872,  0.0328,  0.4162]], requires_grad=True)

In [14]:
for name, child in model.named_children():
    print(name, child)


fc1 Linear(in_features=8, out_features=4, bias=True)
fc2 Linear(in_features=4, out_features=2, bias=True)
fc3 Linear(in_features=2, out_features=1, bias=True)
