### 미니 테스트

스스로 평가 진행 & 부족한 부분 당일 복습 2024. 03. 13. 수


In [1]:
import torch


In [2]:
def print_attr(data):
    print(f'dtype => {data.dtype}')
    print(f'ndim  => {data.ndim}')
    print(f'shape => {data.shape}')
    print(data)


1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 ( )입니다.


> -   Tensor


2. 1번 문제에 해당하는 것의 특징을 간력히 설명해 보세요.


> -   다차원 데이터를 담는 객체
> -   배열이나 행렬과 유사한 자료구조
> -   CPU나 GPU를 사용해 연산 수행 가능


3. Pytorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요. 간단한 데이터 타입의 크기 설명도 함께 작성하세요.


> -   torch.uint8 : 8비트 비부호 정수형 데이터 타입 (0 ~ 255)
> -   torch.int8 : 8비트 정수형 데이터 타입 (-128 ~ 127)
> -   torch.int16 : 16비트 정수형 데이터 타입 (-32,768 ~ 32,767)
> -   torch.int32 : 32비트 정수형 데이터 타입 (-2,147,483,648 ~ 2,147,483,647)
> -   torch.int64 : 64비트 정수형 데이터 타입 (-9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807)


4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.
    - 데이터 : 10 -5 1.4 7 0 -1 0


In [3]:
data1 = torch.tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=torch.bool)
print_attr(data1)


dtype => torch.bool
ndim  => 1
shape => torch.Size([7])
tensor([ True,  True,  True,  True, False,  True, False])


5. 10개의 0 데이터를 2차원으로 저장 코드를 작성하세요.


In [4]:
data2 = torch.zeros((2, 5), dtype=torch.uint8)
print_attr(data2)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([2, 5])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.uint8)


6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요.


In [5]:
data3 = torch.eye(5, 5, dtype=torch.uint8)
print_attr(data3)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([5, 5])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.uint8)


7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.


In [6]:
data4 = torch.eye(5, 5, dtype=torch.uint8) * 3
print_attr(data4)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([5, 5])
tensor([[3, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 3]], dtype=torch.uint8)


8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.
    - 데이터 : 1 ~ 100 범위에서 7의 배수
    - 데이터 타입 : float32
    - 생서 방식 : 공유


In [7]:
import numpy as np
nd_data = np.arange(0, 101, step=7)[1:]
print(nd_data)

data5 = torch.from_numpy(nd_data).float()
print_attr(data5)


[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
dtype => torch.float32
ndim  => 1
shape => torch.Size([14])
tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.])


9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요.
    - 이미지 파일 : flower.jpg 파일
    - 이미지 크기 : 120 x 80
    - 데이터 타입 : int8
    - 데이터 : 임의의 값


In [8]:
img = torch.randint(low=0, high=256, size=(80, 120, 3), dtype=torch.uint8)
print_attr(img)


dtype => torch.uint8
ndim  => 3
shape => torch.Size([80, 120, 3])
tensor([[[149, 243, 169],
         [163,  19, 189],
         [ 57,  25, 247],
         ...,
         [181, 125,  75],
         [229, 249,   0],
         [ 12,  37,   0]],

        [[  1, 200,  98],
         [ 96, 156,  63],
         [247, 225, 159],
         ...,
         [ 58, 122, 163],
         [232, 199,  98],
         [223,  23,  83]],

        [[200, 109, 241],
         [ 45,  43, 249],
         [199, 127,   2],
         ...,
         [139, 216, 192],
         [188,  91,  61],
         [ 33, 139, 105]],

        ...,

        [[ 70,  92, 151],
         [ 77, 219,   3],
         [150, 242, 216],
         ...,
         [218, 168, 145],
         [214, 155, 102],
         [149,  59, 123]],

        [[249,  52,  87],
         [ 34, 118, 137],
         [157, 198, 223],
         ...,
         [198,   9,  60],
         [134, 144, 246],
         [ 19, 128, 181]],

        [[171,  40,  89],
         [ 29,  39,   1],
        

10. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터 : 임의의 정수 10개

-   (1) 1D으로 저장
-   (2) (1)에서 저장된 데이터를 요소 수 변경 없이 3D로 변환
-   (3) (2)에서 저장된 데이터의 2개 차원 변경한 3D로 변환
-   (4) (2)에서 저장된 데이터의 3개 차원 모두 변경한 3D로 변환


In [9]:
random_data = torch.randint(low=0, high=100, size=(10,), dtype=torch.uint8)
print_attr(random_data)

random_data_3D = random_data.view(2, 5)[None]
print_attr(random_data_3D)

random_data_swap2 = random_data_3D.transpose(1, 2)
print_attr(random_data_swap2)

random_data_swap3 = random_data_3D.permute(2, 0, 1)
print_attr(random_data_swap3)


dtype => torch.uint8
ndim  => 1
shape => torch.Size([10])
tensor([37, 91, 54, 23,  1, 66, 98, 16, 71, 47], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([1, 2, 5])
tensor([[[37, 91, 54, 23,  1],
         [66, 98, 16, 71, 47]]], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([1, 5, 2])
tensor([[[37, 66],
         [91, 98],
         [54, 16],
         [23, 71],
         [ 1, 47]]], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([5, 1, 2])
tensor([[[37, 66]],

        [[91, 98]],

        [[54, 16]],

        [[23, 71]],

        [[ 1, 47]]], dtype=torch.uint8)


11. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터
        -   국어 90, 70, 80
        -   영어 70, 100, 80
        -   수학 99, 88, 77

-   (1) 위에 데이터를 저장
-   (2) 과목별 합계, 평균, 최고점수 출력
-   (3) 한 사람의 국어, 영어, 수학 점수 합계, 평균, 최고점수 출력


In [10]:
data6 = torch.tensor([[90, 70, 80], [70, 100, 80], [99, 88, 77]])
print_attr(data6)

data6.sum(dim=1), data6.float().mean(dim=1), data6.max(dim=1)[0]

data6.sum(dim=0), data6.float().mean(dim=0), data6.max(dim=0)[0]


dtype => torch.int64
ndim  => 2
shape => torch.Size([3, 3])
tensor([[ 90,  70,  80],
        [ 70, 100,  80],
        [ 99,  88,  77]])


(tensor([259, 258, 237]),
 tensor([86.3333, 86.0000, 79.0000]),
 tensor([ 99, 100,  80]))

12. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터 1
        -   국어 90, 70, 80
        -   영어 70, 100, 80
        -   수학 99, 88, 77
    -   데이터 2
        -   05, 02, 0.7

-   (1) 위에 데이터를 저장
-   (2) 데이터1과 데이터2의 사칙연산 결과
-   (3) 데이터1과 데이터2의 행렬곱셈


In [11]:
data7 = torch.tensor([[90, 70, 80], [70, 100, 80], [99, 88, 77]])
print_attr(data7)
data8 = torch.tensor([.5, .2, .7])
print_attr(data8)

data7 + data8, data7 - data8, data7 * data8, data7 / data8, data7 ** data8

data7.float().matmul(data8.unsqueeze(1))


dtype => torch.int64
ndim  => 2
shape => torch.Size([3, 3])
tensor([[ 90,  70,  80],
        [ 70, 100,  80],
        [ 99,  88,  77]])
dtype => torch.float32
ndim  => 1
shape => torch.Size([3])
tensor([0.5000, 0.2000, 0.7000])


tensor([[115.],
        [111.],
        [121.]])