### 미니 테스트

스스로 평가 진행 & 부족한 부분 당일 복습 2024. 03. 13. 수


In [1]:
import torch


In [8]:
def print_attr(data):
    print(f'dtype => {data.dtype}')
    print(f'ndim  => {data.ndim}')
    print(f'shape => {data.shape}')
    print(data)


1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 ( )입니다.


> -   Tensor


2. 1번 문제에 해당하는 것의 특징을 간력히 설명해 보세요.


> -   다차원 데이터를 담는 객체
> -   배열이나 행렬과 유사한 자료구조
> -   CPU나 GPU를 사용해 연산 수행 가능


3. Pytorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요. 간단한 데이터 타입의 크기 설명도 함께 작성하세요.


> -   torch.uint8 : 8비트 비부호 정수형 데이터 타입 (0 ~ 255)
> -   torch.int8 : 8비트 정수형 데이터 타입 (-128 ~ 127)
> -   torch.int16 : 16비트 정수형 데이터 타입 (-32,768 ~ 32,767)
> -   torch.int32 : 32비트 정수형 데이터 타입 (-2,147,483,648 ~ 2,147,483,647)
> -   torch.int64 : 64비트 정수형 데이터 타입 (-9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807)


4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.
    - 데이터 : 10 -5 1.4 7 0 -1 0


In [9]:
data1 = torch.tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=torch.bool)
print_attr(data1)


dtype => torch.bool
ndim  => 1
shape => torch.Size([7])
tensor([ True,  True,  True,  True, False,  True, False])


5. 10개의 0 데이터를 2차원으로 저장 코드를 작성하세요.


In [17]:
data2 = torch.zeros((2, 5), dtype=torch.uint8)
print_attr(data2)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([2, 5])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.uint8)


6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요.


In [16]:
data3 = torch.eye(5, 5, dtype=torch.uint8)
print_attr(data3)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([5, 5])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.uint8)


7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.


In [23]:
data4 = torch.eye(5, 5, dtype=torch.uint8) * 3
print_attr(data4)


dtype => torch.uint8
ndim  => 2
shape => torch.Size([5, 5])
tensor([[3, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 3]], dtype=torch.uint8)


8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.
    - 데이터 : 1 ~ 100 범위에서 7의 배수
    - 데이터 타입 : float32
    - 생서 방식 : 공유


In [30]:
import numpy as np
nd_data = np.arange(0, 101, step=7)[1:]
print(nd_data)

data5 = torch.from_numpy(nd_data).float()
print_attr(data5)


[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
dtype => torch.float32
ndim  => 1
shape => torch.Size([14])
tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.])


9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요.
    - 이미지 파일 : flower.jpg 파일
    - 이미지 크기 : 120 x 80
    - 데이터 타입 : int8
    - 데이터 : 임의의 값


In [64]:
img = torch.randint(low=0, high=256, size=(80, 120, 3), dtype=torch.uint8)
print_attr(img)


dtype => torch.uint8
ndim  => 3
shape => torch.Size([80, 120, 3])
tensor([[[130, 241, 155],
         [253, 162, 199],
         [172, 196, 174],
         ...,
         [ 99, 180, 216],
         [129,  42, 253],
         [ 53, 233,  44]],

        [[207, 108, 192],
         [ 38,  43, 224],
         [142, 205, 108],
         ...,
         [236, 137, 238],
         [125, 202, 218],
         [143, 113,  18]],

        [[129,  15,   8],
         [ 50, 204,  33],
         [119, 146, 224],
         ...,
         [193, 210, 159],
         [ 98,  35,  10],
         [165, 105,  76]],

        ...,

        [[129,  53,  86],
         [237,  73, 204],
         [229,  99,  93],
         ...,
         [ 22, 241,  32],
         [ 22,  76, 168],
         [217, 144, 211]],

        [[164,  35, 105],
         [201,  83, 227],
         [231, 204, 243],
         ...,
         [163, 126, 192],
         [115, 169, 184],
         [166, 200, 213]],

        [[133,  91,  20],
         [109, 147,  78],
        

10. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터 : 임의의 정수 10개

-   (1) 1D으로 저장
-   (2) (1)에서 저장된 데이터를 요소 수 변경 없이 3D로 변환
-   (3) (2)에서 저장된 데이터의 2개 차원 변경한 3D로 변환
-   (4) (2)에서 저장된 데이터의 3개 차원 모두 변경한 3D로 변환


In [44]:
random_data = torch.randint(low=0, high=100, size=(10,), dtype=torch.uint8)
print_attr(random_data)

random_data_3D = random_data.view(2, 5)[None]
print_attr(random_data_3D)

random_data_swap2 = random_data_3D.transpose(1, 2)
print_attr(random_data_swap2)

random_data_swap3 = random_data_3D.permute(2, 0, 1)
print_attr(random_data_swap3)


dtype => torch.uint8
ndim  => 1
shape => torch.Size([10])
tensor([13, 30, 40, 98, 17,  7, 24, 71, 84,  6], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([1, 2, 5])
tensor([[[13, 30, 40, 98, 17],
         [ 7, 24, 71, 84,  6]]], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([1, 5, 2])
tensor([[[13,  7],
         [30, 24],
         [40, 71],
         [98, 84],
         [17,  6]]], dtype=torch.uint8)
dtype => torch.uint8
ndim  => 3
shape => torch.Size([5, 1, 2])
tensor([[[13,  7]],

        [[30, 24]],

        [[40, 71]],

        [[98, 84]],

        [[17,  6]]], dtype=torch.uint8)


11. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터
        -   국어 90, 70, 80
        -   영어 70, 100, 80
        -   수학 99, 88, 77

-   (1) 위에 데이터를 저장
-   (2) 과목별 합계, 평균, 최고점수 출력
-   (3) 한 사람의 국어, 영어, 수학 점수 합계, 평균, 최고점수 출력


In [53]:
data6 = torch.tensor([[90, 70, 80], [70, 100, 80], [99, 88, 77]])
print_attr(data6)

data6.sum(dim=1), data6.float().mean(dim=1), data6.max(dim=1)[0]

data6.sum(dim=0), data6.float().mean(dim=0), data6.max(dim=0)[0]


dtype => torch.int64
ndim  => 2
shape => torch.Size([3, 3])
tensor([[ 90,  70,  80],
        [ 70, 100,  80],
        [ 99,  88,  77]])


(tensor([259, 258, 237]),
 tensor([86.3333, 86.0000, 79.0000]),
 tensor([ 99, 100,  80]))

12. 아래 조건에 맞도록 코드를 작성하세요.
    -   데이터 1
        -   국어 90, 70, 80
        -   영어 70, 100, 80
        -   수학 99, 88, 77
    -   데이터 2
        -   05, 02, 0.7

-   (1) 위에 데이터를 저장
-   (2) 데이터1과 데이터2의 사칙연산 결과
-   (3) 데이터1과 데이터2의 행렬곱셈


In [62]:
data7 = torch.tensor([[90, 70, 80], [70, 100, 80], [99, 88, 77]])
print_attr(data7)
data8 = torch.tensor([.5, .2, .7])
print_attr(data8)

data7 + data8, data7 - data8, data7 * data8, data7 / data8, data7 ** data8

data7.float().matmul(data8.unsqueeze(1))


dtype => torch.int64
ndim  => 2
shape => torch.Size([3, 3])
tensor([[ 90,  70,  80],
        [ 70, 100,  80],
        [ 99,  88,  77]])
dtype => torch.float32
ndim  => 1
shape => torch.Size([3])
tensor([0.5000, 0.2000, 0.7000])


tensor([[115.],
        [111.],
        [121.]])