### Tensor shape 변경

-   reshape(), view() : 원소 개수가 유지됨!, 기존 텐서 공유함


In [2]:
# 모듈 로딩
import torch


In [3]:
# 텐서 데이터 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)
print(t1)


torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# [2, 3] ===> [3, 2] 형태 변경 : 원소 동일 6개
t1.view(3,2)


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
# [2, 3] ===> [6, 1] 형태 변경 : 원소 동일 6개
t1.view(6, 1)


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
# [2, 3] ===> [6, 1] 형태 변경 : 원소 동일 6개
# -1 : 원소 수를 알아서 행에 할당
t1.view(-1, 1)


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
# [2, 3] ===> [6, 1] 형태 변경 : 원소 동일 6개
# -1 : 원소 수를 알아서 열에 할당
t1.view(6, -1)


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [8]:
# tensor.reshape()
t1.reshape(-1, 3)


tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# 원소 수 유지되어야 함!
# RuntimeError: shape '[-1, 7]' is invalid for input of size 6
# t1.reshape(-1, 7)


-   전치 : 열<->행 형 변경


In [10]:
print(t1.shape)

t2 = t1.T
print(t2.shape, t2.is_contiguous())


torch.Size([2, 3])
torch.Size([3, 2]) False


In [11]:
# RuntimeError: view size is not compatible with input tensor's size and stride
# t2.view(-1, 6)


In [12]:
t3 = t2.reshape(-1, 6)
print(t3, t3.is_contiguous())


tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 즉 메타데이터

-   현재 저장 형태, 검색 방향 정보, 시작 정보


In [13]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)
print(f't1.storage() => {t1.storage()}')
print(f't1.storage_offset() => {t1.storage_offset()}')
print(f't1.stride() => {t1.stride()}')
print(f't1.is_contiguous() => {t1.is_contiguous()}')


torch.Size([2, 3]) 2
t1.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.is_contiguous() => True


C:\Users\KDP-25\AppData\Local\Temp\ipykernel_6404\3362085813.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(f't1.storage() => {t1.storage()}')


In [14]:
t2 = t1.view(-1, 2)
print(f't2.storage() => {t2.storage()}')
print(f't2.storage_offset() => {t2.storage_offset()}')
print(f't2.stride() => {t2.stride()}')
print(f't2.is_contiguous() => {t2.is_contiguous()}')


t2.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset() => 0
t2.stride() => (2, 1)
t2.is_contiguous() => True


In [15]:
t3 = t1.T
print(f't3.storage() => {t3.storage()}')
print(f't3.storage_offset() => {t3.storage_offset()}')
print(f't3.stride() => {t3.stride()}')
print(f't3.is_contiguous() => {t3.is_contiguous()}')
print(t3.data_ptr(), t3[0].data_ptr(), t3[1].data_ptr())


t3.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t3.storage_offset() => 0
t3.stride() => (1, 3)
t3.is_contiguous() => False
3977466876480 3977466876480 3977466876488


In [16]:
t4 = t3.contiguous()
print(f't4.storage() => {t4.storage()}')
print(f't4.storage_offset() => {t4.storage_offset()}')
print(f't4.stride() => {t4.stride()}')
print(f't4.is_contiguous() => {t4.is_contiguous()}')
print(t4.data_ptr(), t4[0].data_ptr(), t4[1].data_ptr())


t4.storage() =>  1
 4
 2
 5
 3
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t4.storage_offset() => 0
t4.stride() => (2, 1)
t4.is_contiguous() => True
3977466876544 3977466876544 3977466876560


In [17]:
t5 = t3.T
print(f't5.storage() => {t5.storage()}')
print(f't5.storage_offset() => {t5.storage_offset()}')
print(f't5.stride() => {t5.stride()}')
print(f't5.is_contiguous() => {t5.is_contiguous()}')
print(t5.data_ptr(), t5[0].data_ptr(), t5[1].data_ptr())


t5.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t5.storage_offset() => 0
t5.stride() => (3, 1)
t5.is_contiguous() => True
3977466876480 3977466876480 3977466876504


### 차원 제거/추가

-   tensor.squeeze() : 텐서에서 차원이 1인 것 제거
-   tensor.unsqueeze(dim) : 텐서에 차원 1인 것 추가


In [18]:
# 데이터 생성
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]])


In [19]:
print(f't1 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}')
print(f't2 => {t2.shape}, {t2.ndim}D, {t2.data_ptr()}')
print(f't3 => {t3.shape}, {t3.ndim}D, {t3.data_ptr()}')


t1 => torch.Size([2, 2]), 2D, 3977466937344
t2 => torch.Size([1, 4]), 2D, 3977466937472
t3 => torch.Size([1, 1, 4]), 3D, 3977466937536


In [20]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(0)
t55 = t3.squeeze(2)  # dim => shape index
print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}')
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}')
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D, {t33.data_ptr()}')
print(f't3 차원 축소 => {t44.shape}, {t44.ndim}D, {t44.data_ptr()}')
print(f't3 차원 축소 => {t55.shape}, {t55.ndim}D, {t55.data_ptr()}')


t1 차원 축소 => torch.Size([2, 2]), 2D, 3977466937344
t2 차원 축소 => torch.Size([4]), 1D, 3977466937472
t3 차원 축소 => torch.Size([4]), 1D, 3977466937536
t3 차원 축소 => torch.Size([1, 4]), 2D, 3977466937536
t3 차원 축소 => torch.Size([1, 1, 4]), 3D, 3977466937536


In [21]:
## 원소/요소 수 변경 없이 1차원 증가시키기 => torch.unsqueeze(dim)
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}, {t11.stride()}')


t1 정보 => torch.Size([2, 2]), 2D, 3977466937344, (2, 1)


In [22]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)
t33 = t1.unsqueeze(dim=1)
print(f't1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't1 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')
print(f't1 차원 추가 => {t33.shape}, {t33.ndim}D, {t33.data_ptr()}, {t33.stride()}')


t1 차원 추가 => torch.Size([1, 2, 2]), 3D, 3977466937344, (4, 2, 1)
t1 차원 추가 => torch.Size([2, 2, 1]), 3D, 3977466937344, (2, 1, 1)
t1 차원 추가 => torch.Size([2, 1, 2]), 3D, 3977466937344, (2, 2, 1)


### Tensor 차원/형태 변경


In [60]:
t1 = torch.tensor([[[1, 2], [11, 22], [44, 55]]])

print(f't1 => {t1.shape}, {t1.ndim}D, {t1.stride()}, {t1.is_contiguous()}, {t1.data_ptr()}, {t1[0].data_ptr()}')


t1 => torch.Size([1, 3, 2]), 3D, (6, 2, 1), True, 3977466878336, 3977466878336


In [50]:
# 2개의 차원을 변경하는 메서드
t11 = t1.transpose(0, 2)
print(f't11 => {t11.shape}, {t11.ndim}D, {t11.stride()}, {t11.is_contiguous()}, {t11.data_ptr()}, {t11[0].data_ptr()}')


t11 => torch.Size([2, 3, 1]), 3D, (1, 2, 6), False, 3977466877440, 3977466877440


In [51]:
# 모든 차원을 변경하는 메서드
t22 = t1.permute(1, 2, 0)
print(f't22 => {t22.shape}, {t22.ndim}D, {t22.stride()}, {t22.is_contiguous()}, {t22.data_ptr()}, {t22[0].data_ptr()}')


t22 => torch.Size([3, 2, 1]), 3D, (2, 1, 6), True, 3977466877440, 3977466877440


In [52]:
# 모든 차원을 변경하는 메서드
t33 = t1.permute(2, 0, 1)
print(f't33 => {t33.shape}, {t33.ndim}D, {t33.stride()}, {t33.is_contiguous()}, {t33.data_ptr()}, {t3[0].data_ptr()}')


t33 => torch.Size([2, 1, 3]), 3D, (1, 6, 2), False, 3977466877440, 3977466937536


In [40]:
t1.shape


torch.Size([1, 3, 2])

In [44]:
t1[None].shape


torch.Size([1, 1, 3, 2])