### 텐서(Tensor) 살펴보기

-   Pytorch에서 데이터 저장 자료형
-   모델 입력(input), 출력(output) 데이터 형태


-   모듈 로딩


In [1]:
import torch


-   Tensor 속성 관련 함수


In [2]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def printAttribute(tensor: torch, name: str):
    print(f'[ Tensor {name}\'s Attribute ]')
    print(f' - tensor.shape  : {tensor.shape}')
    print(f' - tensor.ndim   : {tensor.ndim}D')
    print(f' - tensor.dtype  : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data\n{tensor.data}')


-   Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    -   타입별 텐서 클래스 생성자 활용
    -   예) IntTensor(), FloatTensor(), BoolTenser()


In [3]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)
t2 = torch.IntTensor([10., 20.])
t3 = torch.BoolTensor([1, 1, 0, -1])
t4 = torch.FloatTensor([10, 20])


C:\Users\KDP-25\AppData\Local\Temp\ipykernel_5716\1414213527.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10., 20.])


In [4]:
printAttribute(t1, 't1')
printAttribute(t2, 't2')
printAttribute(t3, 't3')
printAttribute(t4, 't4')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([10])
 - tensor.ndim   : 1D
 - tensor.dtype  : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([1677726064,       1358,          0,          0,          0,          0,
                 0,          0,          0,          0], dtype=torch.int32)
[ Tensor t2's Attribute ]
 - tensor.shape  : torch.Size([2])
 - tensor.ndim   : 1D
 - tensor.dtype  : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([10, 20], dtype=torch.int32)
[ Tensor t3's Attribute ]
 - tensor.shape  : torch.Size([4])
 - tensor.ndim   : 1D
 - tensor.dtype  : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([ True,  True, False,  True])
[ Tensor t4's Attribute ]
 - tensor.shape  : torch.Size([2])
 - tensor.ndim   : 1D
 - tensor.dtype  : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([10., 20.])


-   Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()


In [5]:
t1 = torch.tensor(10)  # scalar 데이터, int64
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([])
 - tensor.ndim   : 0D
 - tensor.dtype  : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
10


In [6]:
t1 = torch.tensor(10.)  # scalar 데이터, float32
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([])
 - tensor.ndim   : 0D
 - tensor.dtype  : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
10.0


In [7]:
t1 = torch.tensor(10., dtype=torch.int32)  # scalar 데이터, int32
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([])
 - tensor.ndim   : 0D
 - tensor.dtype  : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
10


C:\Users\KDP-25\AppData\Local\Temp\ipykernel_5716\564062794.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1 = torch.tensor(10., dtype=torch.int32)  # scalar 데이터, int32


In [8]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10., dtype=torch.bool)  # scalar 데이터, bool
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([])
 - tensor.ndim   : 0D
 - tensor.dtype  : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
True


In [9]:
t1 = torch.tensor([1, 2, 3], dtype=torch.int8)  # 1D 데이터
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([3])
 - tensor.ndim   : 1D
 - tensor.dtype  : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([1, 2, 3], dtype=torch.int8)


In [10]:
t1 = torch.tensor([[1, 2, 3]], dtype=torch.int8)  # 2D 데이터
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([1, 3])
 - tensor.ndim   : 2D
 - tensor.dtype  : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([[1, 2, 3]], dtype=torch.int8)


-   Tensor 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값


In [11]:
# 0으로 채운 텐서
t1 = torch.zeros((5, 5))
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([5, 5])
 - tensor.ndim   : 2D
 - tensor.dtype  : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
# 1으로 채운 텐서
t1 = torch.ones((2, 4), dtype=torch.int8)
printAttribute(t1, 't1')


[ Tensor t1's Attribute ]
 - tensor.shape  : torch.Size([2, 4])
 - tensor.ndim   : 2D
 - tensor.dtype  : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [13]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like
img = torch.tensor([[1,2,3,4,5,6,7], [2,3,4,5,6,7, 8]])
print(img.shape)


torch.Size([2, 7])


In [14]:
zero_img = torch.zeros_like(img)
print(zero_img)


tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


In [15]:
one_img = torch.ones_like(img)
print(one_img)


tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]])


In [16]:
full_img = torch.full_like(img, 7)
print(full_img)


tensor([[7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7]])


In [17]:
# 대각선 방향으로 1 채운 텐서
t1 = torch.eye(3)
print(t1)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


-   Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()


In [18]:
# 임의의 값으로 채운 텐서
torch.manual_seed(12)
t1 = torch.rand(2, 3)
t2 = torch.randn(2, 3)
t3 = torch.randint(1, 10, (2,3))


In [19]:
print(t1)


tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])


In [20]:
print(t2)


tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])


In [21]:
print(t3)


tensor([[8, 4, 6],
        [2, 2, 2]])


In [22]:
t1 = torch.randn(2, 2, 4)
t1


tensor([[[-0.6958, -0.0522, -0.0351,  0.5274],
         [-0.8227,  0.5942,  0.6618, -0.0125]],

        [[ 1.4400,  0.7946,  0.8444,  1.2668],
         [-1.0249,  1.2336,  0.8366, -2.0645]]])

-   Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch/as_tensor(), tensor()


In [23]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, type(data))


[11 22 33] <class 'numpy.ndarray'>


In [24]:
t1 = torch.from_numpy(data)
print(t1)


tensor([11, 22, 33], dtype=torch.int32)


In [25]:
t2 = torch.as_tensor(data)
print(t2)


tensor([11, 22, 33], dtype=torch.int32)


In [26]:
t3 = torch.tensor(data)
print(t3)


tensor([11, 22, 33], dtype=torch.int32)


In [27]:
# ndarray 원소 변경
data[0] = 100


In [28]:
# from_numpy(), as_tensor() ==> 데이터 공유
# tensor() ==> 복사본 생성
print(data, t1, t2, t3, sep='\n')


[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


-   브로드캐스팅 연산


In [29]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

print(f'm1.shape => {m1.shape}, m2.shape => {m2.shape}')


m1.shape => torch.Size([1, 2]), m2.shape => torch.Size([1])


In [30]:
m3 = m1 + m2
print(f'm3.shape => {m3.shape}\nm3 => \n{m3}')


m3.shape => torch.Size([1, 2])
m3 => 
tensor([[4., 5.]])


In [31]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

print(f'm1.shape => {m1.shape}, m2.shape => {m2.shape}')


m1.shape => torch.Size([1, 2]), m2.shape => torch.Size([2, 1])


In [32]:
m3 = m1 + m2
print(f'm3.shape => {m3.shape}\nm3 => \n{m3}')


m3.shape => torch.Size([2, 2])
m3 => 
tensor([[4., 5.],
        [5., 6.]])


In [33]:
m3 = m1 * m2
m4 = m1.mul(m2)

print(f'm3.shape => {m3.shape}\nm3 => \n{m3}')
print(f'm4.shape => {m4.shape}\nm4 => \n{m4}')


m3.shape => torch.Size([2, 2])
m3 => 
tensor([[3., 6.],
        [4., 8.]])
m4.shape => torch.Size([2, 2])
m4 => 
tensor([[3., 6.],
        [4., 8.]])


In [34]:
# 원소 단위 연산 수행 메서드들
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)


(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))

In [35]:
m1.matmul(m2)


tensor([[11.]])

In [36]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])


In [37]:
m1.matmul(m2)


tensor([[11.]])

In [38]:
m2.matmul(m1)


tensor([[3., 6.],
        [4., 8.]])