### softmax(), sigmoid() 함수 <hr>

-   sigmoid() : y = wx+b 결과 1개 전달 ===> 반환 : 0.0 ~ 1.0 사이 값으로 변환 ==> 이진분류
-   softmax() : y = wx+b 결과 여러개 전달 ===> 반환 : 여러개의 결과값의 합이 1.0이 되도록 변환 ==> 다중분류


In [1]:
## 모듈로딩
import torch                        # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F     # 파이토치 인공신경망 관련 함수들


In [2]:
# 임의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape


torch.Size([5])

In [3]:
F.sigmoid(data1)


tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [4]:
data2 = data1.unsqueeze(dim=0)
data2.shape, data2


(torch.Size([1, 5]), tensor([[1, 2, 1, 1, 2]]))

In [5]:
input = torch.randn(2, 3)
input


tensor([[ 0.2368,  1.0770, -1.1181],
        [ 0.9011, -0.4260, -1.2479]])

In [6]:
output = F.softmax(input, dim=1)
output


tensor([[0.2797, 0.6481, 0.0722],
        [0.7237, 0.1920, 0.0844]])

In [8]:
output.max(dim=1)[1][0].item()


1

In [9]:
output.argmax(dim=1)


tensor([1, 0])