### 인공신경망 모델 클래스 만들기 <hr>

-   부모 클래스 : nn.Module 상속 받음
-   필수 오버라이딩 메서드 : \_\_init\_\_(), forward()


[1] 모듈 로딩 <hr>


In [1]:
import torch
import torch.nn as nn


In [19]:
# 로지스틱회귀 모델 클래스 생성
# - Linear + sigmoid
class LogicLinear(nn.Module):
    # 모델 구조 설정
    def __init__(self, in_, out_):
        super().__init__()
        self.layer1 = nn.Linear(in_, 10)
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(10, out_)
        self.sigmoid2 = nn.Sigmoid()

    # 순방향 학습 진행 콜백함수
    def forward(self, x):
        y = self.layer1(x)
        z = self.sigmoid1(y)
        y = self.layer2(z)
        z = self.sigmoid2(y)
        return z


In [23]:
ll = LogicLinear(784, 3)
print(f"모델 구조 확인 ====>\n{ll}")


모델 구조 확인 ====>
LogicLinear(
  (layer1): Linear(in_features=784, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=3, bias=True)
  (sigmoid2): Sigmoid()
)


In [24]:
print(f"모델구성 W, b ====>")
for param in ll.parameters():
    print(param)


모델구성 W, b ====>
Parameter containing:
tensor([[-0.0210, -0.0260, -0.0137,  ..., -0.0195, -0.0245, -0.0265],
        [ 0.0261, -0.0195,  0.0286,  ...,  0.0237, -0.0272,  0.0190],
        [ 0.0238,  0.0270, -0.0003,  ..., -0.0068, -0.0331, -0.0316],
        ...,
        [ 0.0213, -0.0113, -0.0217,  ..., -0.0151,  0.0276,  0.0248],
        [-0.0204, -0.0132, -0.0047,  ...,  0.0056, -0.0264,  0.0104],
        [ 0.0033,  0.0316, -0.0210,  ..., -0.0156,  0.0279,  0.0094]],
       requires_grad=True)
Parameter containing:
tensor([-0.0147,  0.0121,  0.0187,  0.0307, -0.0187,  0.0105, -0.0084, -0.0148,
        -0.0147, -0.0260], requires_grad=True)
Parameter containing:
tensor([[-0.0355, -0.2211,  0.0203, -0.3026,  0.1681,  0.1947,  0.1003,  0.2202,
         -0.0950,  0.0385],
        [-0.0658, -0.2728,  0.0157,  0.1412,  0.1450,  0.0032,  0.2253, -0.2148,
          0.0935, -0.2027],
        [-0.1965,  0.1119,  0.0830, -0.0959, -0.1037, -0.1337,  0.2691,  0.1109,
          0.1934, -0.0356]], re